/**
 * CagePredict Seed Data
 *
 * Uses realistic fictional UFC-style fighters and events.
 *
 * TO REPLACE WITH REAL UFC DATA:
 * ───────────────────────────────────────────────────────────────
 * 1. Sign up at https://rapidapi.com
 * 2. Subscribe to a UFC/MMA API (search "UFC" or "MMA" on RapidAPI)
 *    Popular options: "UFC Data", "MMA Stats", "Tapology MMA API"
 * 3. Replace the arrays below with API calls:
 *
 *    const response = await fetch('https://mma-stats.p.rapidapi.com/events/upcoming', {
 *      headers: {
 *        'X-RapidAPI-Key': process.env.RAPIDAPI_KEY,
 *        'X-RapidAPI-Host': 'mma-stats.p.rapidapi.com'
 *      }
 *    })
 *    const { events } = await response.json()
 *    // Map events/fighters to our DB schema shape and upsert
 *
 * Official UFC Stats API: https://www.ufc.com/athletes/all (scraper-based)
 * ───────────────────────────────────────────────────────────────
 *
 * Fighter images below use Unsplash placeholder photos.
 * Replace image_url values with actual UFC fighter headshots
 * from the official UFC media library or a licensed photo service.
 */

// ============================================================
// FIGHTER IDs (stable UUIDs for seeding)
// ============================================================
export const FIGHTER_IDS = {
  alexei_petrov:     'f0000001-0000-0000-0000-000000000001',
  marcus_silva:      'f0000001-0000-0000-0000-000000000002',
  kai_tanaka:        'f0000001-0000-0000-0000-000000000003',
  diego_herrera:     'f0000001-0000-0000-0000-000000000004',
  tyler_johnson:     'f0000001-0000-0000-0000-000000000005',
  ahmed_hassan:      'f0000001-0000-0000-0000-000000000006',
  ivan_novak:        'f0000001-0000-0000-0000-000000000007',
  james_powell:      'f0000001-0000-0000-0000-000000000008',
  yuki_shimizu:      'f0000001-0000-0000-0000-000000000009',
  sofia_vargas:      'f0000001-0000-0000-0000-000000000010',
  carlos_mendoza:    'f0000001-0000-0000-0000-000000000011',
  ben_clarke:        'f0000001-0000-0000-0000-000000000012',
  yusuf_arslan:      'f0000001-0000-0000-0000-000000000013',
  kyle_anderson:     'f0000001-0000-0000-0000-000000000014',
  marco_rossi:       'f0000001-0000-0000-0000-000000000015',
  patrick_murphy:    'f0000001-0000-0000-0000-000000000016',
  joaquin_torres:    'f0000001-0000-0000-0000-000000000017',
  max_schultz:       'f0000001-0000-0000-0000-000000000018',
}

export const EVENT_IDS = {
  ufc314: 'e0000001-0000-0000-0000-000000000001',
  ufc315: 'e0000001-0000-0000-0000-000000000002',
}

export const FIGHT_IDS = {
  petrov_silva:   'b0000001-0000-0000-0000-000000000001',
  tanaka_herrera: 'b0000001-0000-0000-0000-000000000002',
  johnson_hassan: 'b0000001-0000-0000-0000-000000000003',
  novak_powell:   'b0000001-0000-0000-0000-000000000004',
  shimizu_vargas: 'b0000001-0000-0000-0000-000000000005',
  mendoza_clarke: 'b0000001-0000-0000-0000-000000000006',
  arslan_anderson:'b0000001-0000-0000-0000-000000000007',
  rossi_murphy:   'b0000001-0000-0000-0000-000000000008',
  torres_schultz: 'b0000001-0000-0000-0000-000000000009',
}

// ============================================================
// FIGHTERS
// ============================================================
export const SEED_FIGHTERS = [
  {
    id: FIGHTER_IDS.alexei_petrov,
    name: 'Alexei Petrov',
    nickname: 'The Savage',
    image_url: 'https://images.unsplash.com/photo-1579126038374-6064e9370f0f?w=400&h=500&fit=crop&q=80',
    nationality: 'Russia',
    flag_emoji: '🇷🇺',
    record: '28-3-0', wins: 28, losses: 3, draws: 0,
    height_cm: 193, reach_cm: 201, weight_class: 'Light Heavyweight', age: 31,
    striking_accuracy: 57.4, td_avg: 1.2, sub_avg: 0.5, sig_str_landed: 5.8,
    analysis: 'Alexei Petrov is a devastating knockout artist with world-class Muay Thai striking. His overhand right has ended careers, and he has 22 of his 28 wins by stoppage. Coming off a dominant five-round title defence, Petrov enters this fight as the clear favourite.',
  },
  {
    id: FIGHTER_IDS.marcus_silva,
    name: 'Marcus Silva',
    nickname: 'The Executioner',
    image_url: 'https://images.unsplash.com/photo-1544117519-31a4b719223d?w=400&h=500&fit=crop&q=80',
    nationality: 'Brazil',
    flag_emoji: '🇧🇷',
    record: '24-2-0', wins: 24, losses: 2, draws: 0,
    height_cm: 190, reach_cm: 198, weight_class: 'Light Heavyweight', age: 28,
    striking_accuracy: 52.1, td_avg: 3.4, sub_avg: 1.8, sig_str_landed: 4.3,
    analysis: 'Marcus Silva is a grappling machine who has submitted 14 of his 24 opponents. He combines wrestling pressure with a dangerous guillotine and rear-naked choke. If he can avoid the early power shots from Petrov and get the fight to the mat, he has a legitimate path to a new title.',
  },
  {
    id: FIGHTER_IDS.kai_tanaka,
    name: 'Kai Tanaka',
    nickname: 'The Samurai',
    image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=500&fit=crop&q=80',
    nationality: 'Japan',
    flag_emoji: '🇯🇵',
    record: '18-2-0', wins: 18, losses: 2, draws: 0,
    height_cm: 175, reach_cm: 180, weight_class: 'Lightweight', age: 27,
    striking_accuracy: 62.3, td_avg: 0.9, sub_avg: 0.4, sig_str_landed: 6.1,
    analysis: 'Kai Tanaka is one of the most technically precise strikers at 155 lbs. His jab-cross combination is textbook perfect, and he possesses elite lateral movement that makes him extremely hard to hit cleanly. On an eight-fight win streak, he looks ready to crack the top 5.',
  },
  {
    id: FIGHTER_IDS.diego_herrera,
    name: 'Diego Herrera',
    nickname: 'El Diablo',
    image_url: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=500&fit=crop&q=80',
    nationality: 'Mexico',
    flag_emoji: '🇲🇽',
    record: '20-3-0', wins: 20, losses: 3, draws: 0,
    height_cm: 173, reach_cm: 176, weight_class: 'Lightweight', age: 30,
    striking_accuracy: 49.8, td_avg: 2.8, sub_avg: 1.1, sig_str_landed: 5.2,
    analysis: 'Diego Herrera fights with unmatched ferocity and crowd-pleasing aggression. He holds the most finishes in lightweight history in a single calendar year and brings elite wrestling to back up his brawling style. Always moves forward and never takes a step back — his pressure alone breaks opponents.',
  },
  {
    id: FIGHTER_IDS.tyler_johnson,
    name: 'Tyler Johnson',
    nickname: 'The Beast',
    image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=500&fit=crop&q=80',
    nationality: 'United States',
    flag_emoji: '🇺🇸',
    record: '15-1-0', wins: 15, losses: 1, draws: 0,
    height_cm: 185, reach_cm: 191, weight_class: 'Middleweight', age: 26,
    striking_accuracy: 54.6, td_avg: 1.6, sub_avg: 0.7, sig_str_landed: 5.0,
    analysis: 'Tyler Johnson is a physical specimen at middleweight with heavy hands and an iron chin. His only professional loss came in a five-round war that many believed he won. A disciplined striker who boxes behind a tight guard, he punishes opponents who leave gaps with accurate counters.',
  },
  {
    id: FIGHTER_IDS.ahmed_hassan,
    name: 'Ahmed Hassan',
    nickname: 'The Pharaoh',
    image_url: 'https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=400&h=500&fit=crop&q=80',
    nationality: 'Egypt',
    flag_emoji: '🇪🇬',
    record: '17-3-0', wins: 17, losses: 3, draws: 0,
    height_cm: 183, reach_cm: 188, weight_class: 'Middleweight', age: 32,
    striking_accuracy: 47.2, td_avg: 4.1, sub_avg: 2.3, sig_str_landed: 3.8,
    analysis: 'Ahmed Hassan is a submission virtuoso with an NCAA wrestling background. His ground control is suffocating, and he has submitted opponents from virtually every position. He prefers to slow the pace down in championship rounds, and his cardio is legendary after competing in three five-round wars this year.',
  },
  {
    id: FIGHTER_IDS.ivan_novak,
    name: 'Ivan Novak',
    nickname: 'The Colossus',
    image_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&h=500&fit=crop&q=80',
    nationality: 'Czech Republic',
    flag_emoji: '🇨🇿',
    record: '12-2-0', wins: 12, losses: 2, draws: 0,
    height_cm: 199, reach_cm: 207, weight_class: 'Heavyweight', age: 29,
    striking_accuracy: 53.1, td_avg: 0.7, sub_avg: 0.3, sig_str_landed: 6.4,
    analysis: 'Ivan Novak is the most naturally powerful heavyweight on the current roster. His right hand is measured at elite punching force, and he has stopped all 10 of his wins by KO or TKO in under two rounds combined. His conditioning has improved dramatically and he no longer fades late.',
  },
  {
    id: FIGHTER_IDS.james_powell,
    name: 'James Powell',
    nickname: 'Big Biscuits',
    image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop&q=80',
    nationality: 'United States',
    flag_emoji: '🇺🇸',
    record: '14-4-0', wins: 14, losses: 4, draws: 0,
    height_cm: 196, reach_cm: 202, weight_class: 'Heavyweight', age: 35,
    striking_accuracy: 45.9, td_avg: 1.4, sub_avg: 0.6, sig_str_landed: 4.7,
    analysis: 'James Powell is a veteran heavyweight who has shared the octagon with multiple champions. His durability is remarkable, and he has recovered from adversity countless times. Big Biscuits fights with calculated aggression and uses his clinch work effectively to neutralize power strikers.',
  },
  {
    id: FIGHTER_IDS.yuki_shimizu,
    name: 'Yuki Shimizu',
    nickname: 'The Dragon',
    image_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=500&fit=crop&q=80',
    nationality: 'Japan',
    flag_emoji: '🇯🇵',
    record: '14-1-0', wins: 14, losses: 1, draws: 0,
    height_cm: 163, reach_cm: 168, weight_class: "Women's Bantamweight", age: 25,
    striking_accuracy: 59.2, td_avg: 1.0, sub_avg: 0.8, sig_str_landed: 5.5,
    analysis: 'Yuki Shimizu is widely considered the most complete female fighter under 135 lbs. A former boxing world champion before transitioning to MMA, her hand speed and combination punching are elite-level. She has not been taken down in her last seven fights.',
  },
  {
    id: FIGHTER_IDS.sofia_vargas,
    name: 'Sofia Vargas',
    nickname: 'La Pantera',
    image_url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=500&fit=crop&q=80',
    nationality: 'Colombia',
    flag_emoji: '🇨🇴',
    record: '12-2-0', wins: 12, losses: 2, draws: 0,
    height_cm: 165, reach_cm: 170, weight_class: "Women's Bantamweight", age: 27,
    striking_accuracy: 51.4, td_avg: 2.9, sub_avg: 1.4, sig_str_landed: 4.6,
    analysis: 'Sofia Vargas is an aggressive pressure fighter who smothers opponents with wrestling and ground-and-pound. She has earned Performance of the Night bonuses in her last three appearances and has finished all but one of her wins. Her relentless pace and power make her a serious danger.',
  },
  {
    id: FIGHTER_IDS.carlos_mendoza,
    name: 'Carlos Mendoza',
    nickname: 'El Toro',
    image_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop&q=80',
    nationality: 'Venezuela',
    flag_emoji: '🇻🇪',
    record: '22-1-0', wins: 22, losses: 1, draws: 0,
    height_cm: 187, reach_cm: 194, weight_class: 'Middleweight', age: 30,
    striking_accuracy: 60.1, td_avg: 1.8, sub_avg: 0.9, sig_str_landed: 5.7,
    analysis: 'Carlos Mendoza is the reigning middleweight champion and widely regarded as the best all-around mixed martial artist on the planet. With elite striking, world-class wrestling, and black belt jiu-jitsu, he presents an unsolvable puzzle to opponents. His IQ inside the octagon is unmatched.',
  },
  {
    id: FIGHTER_IDS.ben_clarke,
    name: 'Ben Clarke',
    nickname: 'The Destroyer',
    image_url: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400&h=500&fit=crop&q=80',
    nationality: 'United Kingdom',
    flag_emoji: '🇬🇧',
    record: '19-2-0', wins: 19, losses: 2, draws: 0,
    height_cm: 186, reach_cm: 193, weight_class: 'Middleweight', age: 29,
    striking_accuracy: 55.8, td_avg: 2.1, sub_avg: 1.2, sig_str_landed: 5.3,
    analysis: 'Ben Clarke has taken the middleweight division by storm with four consecutive first-round finishes. His pressure wrestling combined with lightning-fast uppercuts has drawn comparisons to legendary champions. Clarke has openly stated he intends to finish Mendoza before the judges scorecards, and his record supports that confidence.',
  },
  {
    id: FIGHTER_IDS.yusuf_arslan,
    name: 'Yusuf Arslan',
    nickname: 'The Sultan',
    image_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=500&fit=crop&q=80',
    nationality: 'Turkey',
    flag_emoji: '🇹🇷',
    record: '16-2-0', wins: 16, losses: 2, draws: 0,
    height_cm: 170, reach_cm: 175, weight_class: 'Featherweight', age: 28,
    striking_accuracy: 56.9, td_avg: 1.5, sub_avg: 0.6, sig_str_landed: 5.9,
    analysis: 'Yusuf Arslan is a Muay Thai specialist who has destroyed opponents with his leg kick game. He broke the record for most leg kicks landed in a single fight and has crippled opponents in three straight wins. His footwork is exceptional and he controls distance expertly.',
  },
  {
    id: FIGHTER_IDS.kyle_anderson,
    name: 'Kyle Anderson',
    nickname: 'The Viper',
    image_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=500&fit=crop&q=80',
    nationality: 'United States',
    flag_emoji: '🇺🇸',
    record: '18-3-0', wins: 18, losses: 3, draws: 0,
    height_cm: 168, reach_cm: 173, weight_class: 'Featherweight', age: 31,
    striking_accuracy: 48.3, td_avg: 3.7, sub_avg: 2.0, sig_str_landed: 4.1,
    analysis: 'Kyle Anderson is the most dangerous submission hunter at featherweight. He has submitted opponents in every possible way — guillotine, triangle, arm bar, heel hook, and D\'Arce choke all feature on his highlight reel. Give him any position on the mat and he will find a way to finish you.',
  },
  {
    id: FIGHTER_IDS.marco_rossi,
    name: 'Marco Rossi',
    nickname: 'Ironhead',
    image_url: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=400&h=500&fit=crop&q=80',
    nationality: 'Italy',
    flag_emoji: '🇮🇹',
    record: '13-2-0', wins: 13, losses: 2, draws: 0,
    height_cm: 173, reach_cm: 178, weight_class: 'Bantamweight', age: 26,
    striking_accuracy: 53.7, td_avg: 1.3, sub_avg: 0.5, sig_str_landed: 5.4,
    analysis: 'Marco Rossi earned his nickname through an extraordinary ability to absorb punishment and keep moving forward. His granite chin has absorbed flush shots that would end most careers. Rossi combines body boxing with a powerful left hook that has produced six knockouts in his last eight wins.',
  },
  {
    id: FIGHTER_IDS.patrick_murphy,
    name: 'Patrick Murphy',
    nickname: 'The Ghost',
    image_url: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=400&h=500&fit=crop&q=80',
    nationality: 'Ireland',
    flag_emoji: '🇮🇪',
    record: '15-3-0', wins: 15, losses: 3, draws: 0,
    height_cm: 175, reach_cm: 179, weight_class: 'Bantamweight', age: 30,
    striking_accuracy: 50.1, td_avg: 2.2, sub_avg: 1.6, sig_str_landed: 4.8,
    analysis: 'Patrick Murphy is the most entertaining fighter on the roster and has never had a boring fight. He fights with a carefree attitude and takes risks that no other fighter would dare attempt. Despite three losses, he has won Fight of the Night at every single event he has appeared on.',
  },
  {
    id: FIGHTER_IDS.joaquin_torres,
    name: 'Joaquin Torres',
    nickname: 'The Bull',
    image_url: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=500&fit=crop&q=80',
    nationality: 'Argentina',
    flag_emoji: '🇦🇷',
    record: '17-2-0', wins: 17, losses: 2, draws: 0,
    height_cm: 183, reach_cm: 189, weight_class: 'Welterweight', age: 29,
    striking_accuracy: 58.2, td_avg: 0.8, sub_avg: 0.3, sig_str_landed: 6.3,
    analysis: 'Joaquin Torres is a pure striker who has compiled the highest significant strike accuracy of any welterweight over 15 fights. His combinations end with pinpoint precision and he rarely wastes a shot. After a dominant decision win over the former champion, he is the most feared striker at 170 lbs.',
  },
  {
    id: FIGHTER_IDS.max_schultz,
    name: 'Max Schultz',
    nickname: 'The Hammer',
    image_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=500&fit=crop&q=80',
    nationality: 'Germany',
    flag_emoji: '🇩🇪',
    record: '16-4-0', wins: 16, losses: 4, draws: 0,
    height_cm: 181, reach_cm: 185, weight_class: 'Welterweight', age: 33,
    striking_accuracy: 46.5, td_avg: 3.2, sub_avg: 0.9, sig_str_landed: 4.4,
    analysis: 'Max Schultz is a decorated Olympian in Greco-Roman wrestling who has adapted his skills perfectly to MMA. His throws and trips generate massive ground-and-pound opportunities, and he has developed solid striking to set up his takedowns. A true test for any welterweight.',
  },
]

// ============================================================
// EVENTS + FIGHTS
// ============================================================

// Upcoming dates (relative to project creation — adjust as needed)
const UFC314_DATE = '2025-04-26T22:00:00Z'
const UFC315_DATE = '2025-05-10T22:00:00Z'

export const SEED_EVENTS = [
  {
    id: EVENT_IDS.ufc314,
    name: 'UFC 314: The Final Reckoning',
    date: UFC314_DATE,
    location: 'Las Vegas, NV',
    venue: 'T-Mobile Arena',
    image_url: 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?w=1200&h=600&fit=crop&q=80',
    status: 'upcoming' as const,
    fights: [
      {
        id: FIGHT_IDS.petrov_silva,
        event_id: EVENT_IDS.ufc314,
        fighter1_id: FIGHTER_IDS.alexei_petrov,
        fighter2_id: FIGHTER_IDS.marcus_silva,
        fight_time: `${UFC314_DATE}`,
        status: 'upcoming' as const,
        odds_f1: -175,
        odds_f2: +145,
        is_main_event: true,
        is_title_fight: true,
        weight_class: 'Light Heavyweight',
        display_order: 1,
        analysis_f1: 'Petrov has never been dropped in his career and his striking output at championship pace is unrivalled. Expect him to be wary early, then unleash once he establishes the range with his jab.',
        analysis_f2: 'Silva needs to survive the opening two rounds to succeed. If he can weather Petrov\'s storm and drag the champion into deep water, his submission game in the championship rounds is elite.',
      },
      {
        id: FIGHT_IDS.tanaka_herrera,
        event_id: EVENT_IDS.ufc314,
        fighter1_id: FIGHTER_IDS.kai_tanaka,
        fighter2_id: FIGHTER_IDS.diego_herrera,
        fight_time: UFC314_DATE,
        status: 'upcoming' as const,
        odds_f1: -130,
        odds_f2: +110,
        is_main_event: false,
        is_title_fight: false,
        weight_class: 'Lightweight',
        display_order: 2,
        analysis_f1: 'Tanaka\'s technical precision gives him the edge on the feet. He should control distance and pepper Herrera with clean combinations while staying off the fence.',
        analysis_f2: 'Herrera must close the distance quickly and use his wrestling to nullify Tanaka\'s technique. His pressure is relentless but can he get inside Tanaka\'s jab?',
      },
      {
        id: FIGHT_IDS.johnson_hassan,
        event_id: EVENT_IDS.ufc314,
        fighter1_id: FIGHTER_IDS.tyler_johnson,
        fighter2_id: FIGHTER_IDS.ahmed_hassan,
        fight_time: UFC314_DATE,
        status: 'upcoming' as const,
        odds_f1: -110,
        odds_f2: -110,
        is_main_event: false,
        is_title_fight: false,
        weight_class: 'Middleweight',
        display_order: 3,
        analysis_f1: 'Johnson\'s striking defence is excellent and he uses his reach to keep opponents at distance. He needs to avoid the clinch where Hassan\'s wrestling becomes lethal.',
        analysis_f2: 'Hassan\'s path to victory is clear: get the fight to the ground and submit. He has the wrestling to achieve it but must be prepared to eat some hard shots on the way in.',
      },
      {
        id: FIGHT_IDS.novak_powell,
        event_id: EVENT_IDS.ufc314,
        fighter1_id: FIGHTER_IDS.ivan_novak,
        fighter2_id: FIGHTER_IDS.james_powell,
        fight_time: UFC314_DATE,
        status: 'upcoming' as const,
        odds_f1: -200,
        odds_f2: +165,
        is_main_event: false,
        is_title_fight: false,
        weight_class: 'Heavyweight',
        display_order: 4,
        analysis_f1: 'Novak\'s pure power is terrifying. He has the highest KO% among active heavyweights and his right hand is a genuine fight-ender. This could be over in seconds if Powell is careless.',
        analysis_f2: 'Powell is the veteran who has seen it all before. He will not be intimidated and his clinch game could slow Novak down. Powell needs to survive the opening rounds and tire the younger man.',
      },
      {
        id: FIGHT_IDS.shimizu_vargas,
        event_id: EVENT_IDS.ufc314,
        fighter1_id: FIGHTER_IDS.yuki_shimizu,
        fighter2_id: FIGHTER_IDS.sofia_vargas,
        fight_time: UFC314_DATE,
        status: 'upcoming' as const,
        odds_f1: -160,
        odds_f2: +135,
        is_main_event: false,
        is_title_fight: false,
        weight_class: "Women's Bantamweight",
        display_order: 5,
        analysis_f1: 'Shimizu is the superior striker in this matchup and her ability to stay on her feet has been consistent. The question is whether she can stuff Vargas\'s takedown attempts for a full three rounds.',
        analysis_f2: 'Vargas has the ground game to change the fight dramatically. Her top pressure and ground-and-pound output is exceptional. Getting the fight to the mat and keeping it there is her blueprint to upset.',
      },
    ],
  },
  {
    id: EVENT_IDS.ufc315,
    name: 'UFC 315: Night of Champions',
    date: UFC315_DATE,
    location: 'Miami, FL',
    venue: 'Kaseya Center',
    image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&h=600&fit=crop&q=80',
    status: 'upcoming' as const,
    fights: [
      {
        id: FIGHT_IDS.mendoza_clarke,
        event_id: EVENT_IDS.ufc315,
        fighter1_id: FIGHTER_IDS.carlos_mendoza,
        fighter2_id: FIGHTER_IDS.ben_clarke,
        fight_time: UFC315_DATE,
        status: 'upcoming' as const,
        odds_f1: -145,
        odds_f2: +122,
        is_main_event: true,
        is_title_fight: true,
        weight_class: 'Middleweight',
        display_order: 1,
        analysis_f1: 'Mendoza\'s complete game means Clarke cannot rely on any one area to dominate. The champion will mix levels, use his clinch work, and stay disciplined throughout. Expect a chess match from Mendoza.',
        analysis_f2: 'Clarke\'s finishing ability is the great equaliser. He can end this in any round with his uppercut or takedown-into-ground-and-pound game. The challenger has never been finished himself — this will go the distance if Clarke can\'t find the finish.',
      },
      {
        id: FIGHT_IDS.arslan_anderson,
        event_id: EVENT_IDS.ufc315,
        fighter1_id: FIGHTER_IDS.yusuf_arslan,
        fighter2_id: FIGHTER_IDS.kyle_anderson,
        fight_time: UFC315_DATE,
        status: 'upcoming' as const,
        odds_f1: -125,
        odds_f2: +105,
        is_main_event: false,
        is_title_fight: false,
        weight_class: 'Featherweight',
        display_order: 2,
        analysis_f1: 'Arslan will target Anderson\'s lead leg mercilessly from the opening bell. His leg kicks have a cumulative effect that compromises opponents\' movement and ultimately leaves them flatfooted.',
        analysis_f2: 'Anderson knows he cannot allow this to become a striking contest on the feet. His sole path to victory runs through the mat, and he has the wrestling credentials to get it there. The question is eating those leg kicks on the way in.',
      },
      {
        id: FIGHT_IDS.rossi_murphy,
        event_id: EVENT_IDS.ufc315,
        fighter1_id: FIGHTER_IDS.marco_rossi,
        fighter2_id: FIGHTER_IDS.patrick_murphy,
        fight_time: UFC315_DATE,
        status: 'upcoming' as const,
        odds_f1: -140,
        odds_f2: +118,
        is_main_event: false,
        is_title_fight: false,
        weight_class: 'Bantamweight',
        display_order: 3,
        analysis_f1: 'Rossi is the more technically sound fighter and his body work over three rounds could break Murphy down. He has to avoid getting drawn into a brawl where Murphy\'s chaos becomes an equaliser.',
        analysis_f2: 'Murphy makes fights unpredictable and that could work in his favour here. If he can land his left hook early and hurt Rossi, this becomes wide open. Murphy has never been knocked out despite fighting brawling style.',
      },
      {
        id: FIGHT_IDS.torres_schultz,
        event_id: EVENT_IDS.ufc315,
        fighter1_id: FIGHTER_IDS.joaquin_torres,
        fighter2_id: FIGHTER_IDS.max_schultz,
        fight_time: UFC315_DATE,
        status: 'upcoming' as const,
        odds_f1: -165,
        odds_f2: +138,
        is_main_event: false,
        is_title_fight: false,
        weight_class: 'Welterweight',
        display_order: 4,
        analysis_f1: 'Torres\'s precision striking will pick Schultz apart if the fight stays standing. His accuracy rate is the highest at welterweight and he counters takedown attempts with punishing strikes.',
        analysis_f2: 'Schultz needs a quick takedown before Torres finds his range. His Greco-Roman throws are spectacular, and one clean trip could completely flip this fight and allow his ground-and-pound to do damage.',
      },
    ],
  },
]
